name: CI-pact-util-lib


on:
  push:

  workflow_dispatch:


jobs:
  UT:
    runs-on: ubuntu-latest
    steps:

      - uses: actions/checkout@v2

      - name: Install Pact
        run: |
          wget -nv https://github.com/kadena-io/pact-5/releases/download/5.1/pact-5.1-linux-x64.tar.gz
          mkdir -p .bin/
          tar -xz -C .bin/ -f pact-5.1-linux-x64.tar.gz ./pact
          chmod +x .bin/pact

      - name: Print hashes
        run: .bin/pact -t pact/print-mod-hashs.repl | grep -e "^H:"

      - name: Test util-chain-data
        run: |
          .bin/pact -t pact/tests_repl/util-chain-data.repl 2>&1 | tee out.txt
          if ! grep -q "FAILURE" out.txt; then echo "OK"; exit 0; else echo "Fail";exit 1; fi

      - name: Test util-lists
        run: |
          .bin/pact -t pact/tests_repl/util-lists-test.repl 2>&1 | tee out.txt
          if ! grep -q "FAILURE" out.txt; then echo "OK"; exit 0; else echo "Fail";exit 1; fi

      - name: Test util-strings
        run: |
          .bin/pact -t pact/tests_repl/util-strings-test.repl 2>&1 | tee out.txt
          if ! grep -q "FAILURE" out.txt; then echo "OK"; exit 0; else echo "Fail";exit 1; fi

      - name: Test util-math
        run: |
          .bin/pact -t pact/tests_repl/util-math-test.repl 2>&1 | tee out.txt
          if ! grep -q "FAILURE" out.txt; then echo "OK"; exit 0; else echo "Fail";exit 1; fi

      - name: Test util-random
        run: |
          .bin/pact -t pact/tests_repl/util-random-test.repl 2>&1 | tee out.txt
          if ! grep -q "FAILURE" out.txt; then echo "OK"; exit 0; else echo "Fail";exit 1; fi

      - name: Test util-time
        run: |
          .bin/pact -t pact/tests_repl/util-time-test.repl 2>&1 | tee out.txt
          if ! grep -q "FAILURE" out.txt; then echo "OK"; exit 0; else echo "Fail";exit 1; fi

      - name: Test util-fungible
        run: |
          .bin/pact -t pact/tests_repl/util-fungible-test.repl 2>&1 | tee out.txt
          if ! grep -q "FAILURE" out.txt; then echo "OK"; exit 0; else echo "Fail";exit 1; fi

      - name: Test util-zk
        run: |
          .bin/pact -t pact/tests_repl/util-zk-test.repl 2>&1 | tee out.txt
          if ! grep -q "FAILURE" out.txt; then echo "OK"; exit 0; else echo "Fail";exit 1; fi
